name: Docker CICD
on:
  push:
    branchs:
      - main
jobs:
  say-hello:
    runs-on: self-hosted
    steps:
      - run: echo "hello world !"
      - run: |
          /home/duy/actions-runner/_work/test-ci/test-ci/hello.sh
