name: hello world
on:
  push:
    branchs: [main]
jobs:
  say-hello:
    runs-on: duy3
    steps:
      - run: echo " hello world"
      - uses: actions/checkout@v3
      - run: |
          load.sh
          list-image.sh
  
  
